language: node_js
node_js:
  - 12 # uses version 12
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "polishd-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm test # test the code
  - npm run build-client # make the bundle
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: polishd
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: kSmJ45ag3AGpYab5QFsn1C/yJW1G0C/PpKrPb1HiBUM0WnIwY0DDBDfZi22wINnStXeDJC68nz23QN6SeaCfZ4YUn1Z8tt1NYsie/zIeM6rotW/Umkwkc8Zm992Ovjar4cm69Has/swSL6HFPStgdPnFUxZRO9svIYTZt+OwXR7Dq6FTpGnhx/syWO2YZlbS7/IcOWWTngFauvRcw+ltP3ZwexiOaLY/uTOX8SGp1vrS6vTlBXjAHv98Qex1v9+tTIosQnq7X32D24BnLbZDNAHe0FhwMoIA6JDH5EM3mn6e4jG+mAK9z8yg1wr9ID7jVjc7++FevjjDop6TaXs2m1M6Nc5Wnndp3N6/3RPvWIN4JjTffJOX+kpBFD0cO5vkEyLzN0DziWSppV6HIRsnE+jdwUOAC8t+BB6df9VWm+51MBSlSust7LowYeYIayL5yBuIvaMjpX/AUIPBvYvVpbvf1wVLBzMjr4c+dvzNg6up5phReVhOwcZnwjpZhr3nrH9SUBipE89y6U1Cpt9fr2Cqm5JfAKcFAr10rK4DkGEV4KCakN1rc4ySQKw/hNpGGySCLGGwr7+6aFwsxP+Hnj/tPKL5KC4E6TYWeOov0f8goMDD7VgryLjymZwVv4q7GXu3D2VdRdPHAJFXPXHoR58JlQOUrUkMDj1bXv5vaH8=
